nelmio_api_doc:
    documentation:
        info:
            title: MyQ App
            description: MyQ App API documentation!
            version: 1.0.0
        components:
            schemas:
                ValidationFailedException:
                    description: "Validation failed exception"
                    type: object
                    properties:
                        title:
                            type: string
                            example: 'Validation failed with N error(s).'
                        errors:
                            type: array
                            items:
                                type: string
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
