version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Install dependencies
      - sh AWS-ssm.sh
      - composer install --ignore-platform-req=ext-sodium
      - php bin/console assets:install --symlink || true
      - php bin/console lexik:jwt:generate-keypair || true
      - php bin/console doctrine:migrations:migrate
  post_build:
    commands:
      - echo Build completed on `date`