monolog:
    channels: [ app ]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        doctrine:
            type: service
            id: App\Util\Monolog\DatabaseHandler
            level: info
            channels: [app]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
