location / {
  index index.html;
  try_files $uri $uri/ /index.html;
}

location /api/ {
    try_files $uri @rewriteapp;
}

location /media/ {

}

location /bundles/ {

}

location @rewriteapp {
    rewrite ^(.*)$ /index.php/$1 last;
}
